# Generated by Django 4.2.11 on 2024-04-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=30)),
                ("accessType", models.IntegerField()),
            ],
        ),
    ]
