# Generated by Django 4.2.11 on 2024-04-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="loginid",
            field=models.CharField(default="null", max_length=30),
        ),
    ]
