# Generated by Django 4.2.11 on 2024-04-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_user_loginid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Programs",
            fields=[
                ("pid", models.AutoField(primary_key=True, serialize=False)),
                ("programName", models.CharField(max_length=30)),
                ("version", models.CharField(max_length=30)),
                ("release", models.CharField(max_length=30)),
            ],
        ),
    ]
