# Generated by Django 4.2.11 on 2024-04-21 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_programarea"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportUp",
            fields=[
                ("rid", models.AutoField(primary_key=True, serialize=False)),
                ("programName", models.CharField(max_length=50)),
                ("bugType", models.CharField(max_length=30)),
                ("severity", models.CharField(max_length=30)),
                ("reproducible", models.CharField(max_length=10)),
                ("summary", models.CharField(max_length=150)),
                ("problem", models.CharField(max_length=300)),
                ("suggestedFix", models.CharField(max_length=300)),
                ("reportBy", models.CharField(max_length=30)),
                ("date", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
