# Generated by Django 4.2.11 on 2024-04-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_reportup_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportup",
            name="date",
            field=models.DateTimeField(default="2024-04-21 01:51:01 UTC"),
        ),
    ]
