# Generated by Django 4.2.11 on 2024-04-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_reportup_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportDown",
            fields=[
                ("rdid", models.AutoField(primary_key=True, serialize=False)),
                ("rid", models.IntegerField()),
                ("functionArea", models.CharField(max_length=100)),
                ("AssignTo", models.CharField(max_length=30)),
                ("comments", models.CharField(max_length=300)),
                ("status", models.CharField(max_length=30)),
                ("priority", models.CharField(max_length=100)),
                ("resolution", models.CharField(max_length=30)),
                ("resolutionVersion", models.CharField(max_length=30)),
                ("resolvedBy", models.CharField(max_length=30)),
                ("resolveDate", models.DateTimeField(default="2024-04-23")),
                ("testedBy", models.CharField(max_length=30)),
                ("testedDate", models.DateTimeField(default="2024-04-23")),
                ("deferred", models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name="reportup",
            name="date",
            field=models.DateTimeField(default="2024-04-23"),
        ),
    ]
