# Generated by Django 4.2.11 on 2024-04-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_reportdown_alter_reportup_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportup",
            name="status",
            field=models.CharField(default="open", max_length=30),
        ),
    ]
