# Generated by Django 4.2.11 on 2024-04-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_reportup_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportup",
            name="assignTo",
            field=models.CharField(default="Felix", max_length=30),
        ),
        migrations.AlterField(
            model_name="reportdown",
            name="resolveDate",
            field=models.DateTimeField(default="2024-04-24"),
        ),
        migrations.AlterField(
            model_name="reportdown",
            name="testedDate",
            field=models.DateTimeField(default="2024-04-24"),
        ),
        migrations.AlterField(
            model_name="reportup",
            name="date",
            field=models.DateTimeField(default="2024-04-24"),
        ),
    ]
