# Generated by Django 4.2.11 on 2024-04-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_reportup_assignto_alter_reportdown_resolvedate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportdown",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="reportdown",
            name="text",
            field=models.TextField(null=True),
        ),
    ]
