# Generated by Django 4.2.11 on 2024-04-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_remove_reportdown_image_remove_reportdown_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportdown",
            name="file",
            field=models.FileField(null=True, upload_to="documents/"),
        ),
    ]
