# Generated by Django 4.2.11 on 2024-04-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_reportdown_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportdown",
            name="file",
            field=models.CharField(default="false", max_length=30),
        ),
    ]
